name: rust

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    check:
        name: check
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install latest nightly
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly
                    override: true
            -   name: Cache cargo registry
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/registry
                    key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo index
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/git
                    key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo build
                uses: actions/cache@v1
                with:
                    path: target
                    key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
            -   name: Run cargo check
                uses: actions-rs/cargo@v1
                with:
                    command: check
                    args: --features "strict"

    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install latest nightly
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly
                    override: true
            -   name: Cache cargo registry
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/registry
                    key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo index
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/git
                    key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo build
                uses: actions/cache@v1
                with:
                    path: target
                    key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
            -   uses: actions-rs/cargo@v1
                with:
                    command: test
                    args: --features "strict"

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install latest nightly
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly
                    override: true
            -   run: rustup component add rustfmt
            -   uses: actions-rs/cargo@v1
                with:
                    command: fmt
                    args: --all -- --check

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install latest nightly-2020-04-06
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly-2020-04-06
                    override: true
            -   name: Cache cargo registry
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/registry
                    key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo index
                uses: actions/cache@v1
                with:
                    path: ~/.cargo/git
                    key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo build
                uses: actions/cache@v1
                with:
                    path: target
                    key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
            -   run: rustup component add clippy
            -   uses: actions-rs/cargo@v1
                with:
                    command: clippy
                    args: --features "strict"